# Generated by Django 5.0.1 on 2025-10-24 02:38

import django.core.validators
import django.db.models.deletion
import taggit.managers
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('taggit', '0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField(blank=True)),
                ('color', models.CharField(choices=[('blue', 'Blue'), ('green', 'Green'), ('yellow', 'Yellow'), ('red', 'Red'), ('purple', 'Purple')], default='blue', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Prompt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, validators=[django.core.validators.MinLengthValidator(3)])),
                ('content', models.TextField(validators=[django.core.validators.MinLengthValidator(10)])),
                ('is_template', models.BooleanField(default=False)),
                ('variables', models.JSONField(blank=True, default=list, help_text="템플릿 변수 목록 (예: ['language', 'feature'])")),
                ('color_label', models.CharField(choices=[('ready', '🟢 Ready to use'), ('draft', '🟡 Draft'), ('template', '🔵 Template'), ('update', '🔴 Needs Update')], default='ready', max_length=20)),
                ('is_favorite', models.BooleanField(default=False)),
                ('is_public', models.BooleanField(default=False)),
                ('use_count', models.PositiveIntegerField(default=0)),
                ('last_used', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prompts', to='prompts.category')),
                ('tags', taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prompts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PromptUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('used_at', models.DateTimeField(auto_now_add=True)),
                ('variables_used', models.JSONField(blank=True, help_text='사용 시 적용한 변수 값', null=True)),
                ('prompt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usages', to='prompts.prompt')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-used_at'],
            },
        ),
        migrations.AddIndex(
            model_name='prompt',
            index=models.Index(fields=['user', '-created_at'], name='prompts_pro_user_id_6fdc10_idx'),
        ),
        migrations.AddIndex(
            model_name='prompt',
            index=models.Index(fields=['-use_count'], name='prompts_pro_use_cou_ee584b_idx'),
        ),
        migrations.AddIndex(
            model_name='prompt',
            index=models.Index(fields=['is_favorite', '-last_used'], name='prompts_pro_is_favo_25b713_idx'),
        ),
        migrations.AddIndex(
            model_name='prompt',
            index=models.Index(fields=['category', '-created_at'], name='prompts_pro_categor_50ceb9_idx'),
        ),
        migrations.AddIndex(
            model_name='promptusage',
            index=models.Index(fields=['prompt', '-used_at'], name='prompts_pro_prompt__ab541d_idx'),
        ),
        migrations.AddIndex(
            model_name='promptusage',
            index=models.Index(fields=['user', '-used_at'], name='prompts_pro_user_id_40783c_idx'),
        ),
    ]
